.TH "Porto_Pontos Directory Reference" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Porto_Pontos Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCities\fP"
.br
.ti -1c
.RI "directory \fBClient\fP"
.br
.ti -1c
.RI "directory \fBClient_Linked_List\fP"
.br
.ti -1c
.RI "directory \fBClient_Node\fP"
.br
.ti -1c
.RI "directory \fBDate\fP"
.br
.ti -1c
.RI "directory \fBPoi\fP"
.br
.ti -1c
.RI "directory \fBPoints\fP"
.br
.ti -1c
.RI "directory \fBTrips\fP"
.br
.in -1c
