.TH "city" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
city \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cities\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBdescription\fP"
.br
.ti -1c
.RI "\fBPOINTS\fP \fBcoordinates\fP"
.br
.ti -1c
.RI "\fBPOI\fP * \fBpoi\fP"
.br
.ti -1c
.RI "int \fBnum_of_poi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file cities\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBPOINTS\fP coordinates"

.PP
Definition at line 15 of file cities\&.h\&.
.SS "char* description"

.PP
Definition at line 14 of file cities\&.h\&.
.SS "char* name"

.PP
Definition at line 13 of file cities\&.h\&.
.SS "int num_of_poi"

.PP
Definition at line 17 of file cities\&.h\&.
.SS "\fBPOI\fP* \fBpoi\fP"

.PP
Definition at line 16 of file cities\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
