.TH "client" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBVAT\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBaddress\fP"
.br
.ti -1c
.RI "uint32_t \fBphone_number\fP"
.br
.ti -1c
.RI "\fBDATE\fP \fBbirth\fP"
.br
.ti -1c
.RI "\fBDATE\fP \fBregistration\fP"
.br
.ti -1c
.RI "\fBCOUNTRY\fP * \fBbooked_trips\fP"
.br
.ti -1c
.RI "int \fBsize_booked_trips\fP"
.br
.ti -1c
.RI "\fBCOUNTRY\fP * \fBfinished_trips\fP"
.br
.ti -1c
.RI "int \fBsize_finished_trips\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file client\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* address"

.PP
Definition at line 16 of file client\&.h\&.
.SS "\fBDATE\fP birth"

.PP
Definition at line 18 of file client\&.h\&.
.SS "\fBCOUNTRY\fP* booked_trips"

.PP
Definition at line 20 of file client\&.h\&.
.SS "\fBCOUNTRY\fP* finished_trips"

.PP
Definition at line 22 of file client\&.h\&.
.SS "char* name"

.PP
Definition at line 15 of file client\&.h\&.
.SS "uint32_t phone_number"

.PP
Definition at line 17 of file client\&.h\&.
.SS "\fBDATE\fP registration"

.PP
Definition at line 19 of file client\&.h\&.
.SS "int size_booked_trips"

.PP
Definition at line 21 of file client\&.h\&.
.SS "int size_finished_trips"

.PP
Definition at line 23 of file client\&.h\&.
.SS "uint32_t VAT"

.PP
Definition at line 14 of file client\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
