.TH "client_node" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client_node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client_node\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCLIENT\fP \fBclient\fP"
.br
.ti -1c
.RI "struct \fBclient_node\fP * \fBnext_node\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file client_node\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBCLIENT\fP \fBclient\fP"

.PP
Definition at line 11 of file client_node\&.h\&.
.SS "struct \fBclient_node\fP* next_node"

.PP
Definition at line 12 of file client_node\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
