.TH "Porto_Pontos/Client/client.h" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Porto_Pontos/Client/client.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Trips/trips\&.h'\fP
.br
\fC#include 'Date/date\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBclient\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBclient\fP \fBCLIENT\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbook_trip\fP (\fBCLIENT\fP *\fBclient\fP, char *country_name)"
.br
.ti -1c
.RI "void \fBfinish_trip_requisite\fP (\fBCLIENT\fP *\fBclient\fP, char *country_name)"
.br
.ti -1c
.RI "void \fBfinish_trip\fP (\fBCLIENT\fP *\fBclient\fP, \fBCOUNTRY\fP *booked_trip)"
.br
.ti -1c
.RI "void \fBremove_trip\fP (\fBCLIENT\fP *\fBclient\fP, char *country_name)"
.br
.ti -1c
.RI "void \fBedit_trip\fP (\fBCLIENT\fP *\fBclient\fP, char *current_country_name, char *new_country_name)"
.br
.ti -1c
.RI "\fBCOUNTRY\fP * \fBsearch_trip\fP (\fBCLIENT\fP *\fBclient\fP, char *country_name, bool is_finished)"
.br
.ti -1c
.RI "void \fBprint_trips\fP (\fBCLIENT\fP *\fBclient\fP, bool is_finished)"
.br
.ti -1c
.RI "void \fBprint_finished_trip_specific\fP (\fBCLIENT\fP *\fBclient\fP, char *country_name, char *city_name, char *\fBpoi\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBclient\fP  \fBCLIENT\fP"

.SH "Function Documentation"
.PP 
.SS "void book_trip (\fBCLIENT\fP * client, char * country_name)"
books a trip for a client 
.PP
\fBParameters:\fP
.RS 4
\fIclient\fP client 
.br
\fIcountry_name\fP country name to insert 
.RE
.PP

.PP
Definition at line 24 of file client\&.c\&.
.SS "void edit_trip (\fBCLIENT\fP * client, char * current_country_name, char * new_country_name)"
edits a booked trip from a client 
.PP
\fBParameters:\fP
.RS 4
\fIclient\fP client 
.br
\fIcurrent_country_name\fP current countries name 
.br
\fInew_country_name\fP new countries name 
.RE
.PP

.PP
Definition at line 91 of file client\&.c\&.
.SS "void finish_trip (\fBCLIENT\fP * client, \fBCOUNTRY\fP * booked_trip)"
finishes a trip for a client from his booked trips 
.PP
\fBParameters:\fP
.RS 4
\fIclient\fP client 
.br
\fIbooked_trip\fP client booked trips 
.RE
.PP

.PP
Definition at line 58 of file client\&.c\&.
.SS "void finish_trip_requisite (\fBCLIENT\fP * client, char * country_name)"
inserts a finished trip into a client 
.PP
\fBParameters:\fP
.RS 4
\fIclient\fP client 
.br
\fIcountry_name\fP country_name 
.RE
.PP

.PP
Definition at line 41 of file client\&.c\&.
.SS "void print_finished_trip_specific (\fBCLIENT\fP * client, char * country_name, char * city_name, char * poi)"
prints finished trips with specific content 
.PP
\fBParameters:\fP
.RS 4
\fIclient\fP client 
.br
\fIcountry_name\fP country name 
.br
\fIcity_name\fP city name 
.br
\fIpoi\fP point of interest name 
.RE
.PP

.PP
Definition at line 118 of file client\&.c\&.
.SS "void print_trips (\fBCLIENT\fP * client, bool is_finished)"
prints trips from a client 
.PP
\fBParameters:\fP
.RS 4
\fIclient\fP client 
.br
\fIis_finished\fP 0: print booked trips || 1: print finished trips 
.RE
.PP

.PP
Definition at line 110 of file client\&.c\&.
.SS "void remove_trip (\fBCLIENT\fP * client, char * country_name)"
removes a booked trip from a client 
.PP
\fBParameters:\fP
.RS 4
\fIclient\fP client client 
.br
\fIcountry_name\fP country name to remove 
.RE
.PP

.PP
Definition at line 77 of file client\&.c\&.
.SS "\fBCOUNTRY\fP* search_trip (\fBCLIENT\fP * client, char * country_name, bool is_finished)"
searches for a trip from a client 
.PP
\fBParameters:\fP
.RS 4
\fIclient\fP client 
.br
\fIcountry_name\fP country name 
.br
\fIis_finished\fP 0: booked trips array | 1: finished trip array 
.RE
.PP
\fBReturns:\fP
.RS 4
trip 
.RE
.PP

.PP
Definition at line 102 of file client\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
