.TH "Porto_Pontos/Client_Linked_List/client_linked_list.h" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Porto_Pontos/Client_Linked_List/client_linked_list.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Client_Node/client_node\&.h'\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBclient_linked_list\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBclient_linked_list\fP \fBCLIENT_LL\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinsert_client\fP (\fBCLIENT_LL\fP *list, bool at_head, char *name, uint32_t VAT, char *address, uint32_t phone_number, int birth_day, int birth_month, int birth_year)"
.br
.ti -1c
.RI "void \fBinsert_client_sorted\fP (\fBCLIENT_LL\fP *list, char *name, uint32_t VAT, char *address, uint32_t phone_number, int birth_day, int birth_month, int birth_year)"
.br
.ti -1c
.RI "\fBCLIENT\fP * \fBsearch_client\fP (\fBCLIENT_LL\fP *list, const char *client_name)"
.br
.ti -1c
.RI "void \fBremove_client\fP (\fBCLIENT_LL\fP *list, char *client_name)"
.br
.ti -1c
.RI "void \fBprint_clients\fP (\fBCLIENT_LL\fP *list)"
.br
.ti -1c
.RI "void \fBsort_clients\fP (\fBCLIENT_LL\fP *list)"
.br
.ti -1c
.RI "void \fBclient_report_txt\fP (\fBCLIENT_LL\fP *list, char *filename)"
.br
.ti -1c
.RI "void \fBread_list_txt\fP (\fBCLIENT_LL\fP *list, char *filename)"
.br
.ti -1c
.RI "void \fBsave_list_txt\fP (\fBCLIENT_LL\fP *list, char *filename)"
.br
.ti -1c
.RI "void \fBread_list_bin\fP (\fBCLIENT_LL\fP *list, char *filename)"
.br
.ti -1c
.RI "void \fBsave_list_bin\fP (\fBCLIENT_LL\fP *list, char *filename)"
.br
.ti -1c
.RI "void \fBdeallocate_client_linked_list\fP (\fBCLIENT_LL\fP *list)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBclient_linked_list\fP  \fBCLIENT_LL\fP"

.SH "Function Documentation"
.PP 
.SS "void client_report_txt (\fBCLIENT_LL\fP * list, char * filename)"
saves clients info to \&.txt file 
.PP
\fBParameters:\fP
.RS 4
\fIlist\fP linked list 
.br
\fIfilename\fP file name 
.RE
.PP

.PP
Definition at line 142 of file client_linked_list\&.c\&.
.SS "void deallocate_client_linked_list (\fBCLIENT_LL\fP * list)"

.PP
Definition at line 277 of file client_linked_list\&.c\&.
.SS "void insert_client (\fBCLIENT_LL\fP * list, bool at_head, char * name, uint32_t VAT, char * address, uint32_t phone_number, int birth_day, int birth_month, int birth_year)"
insert client into linked list 
.PP
\fBParameters:\fP
.RS 4
\fIlist\fP linked list 
.br
\fIat_head\fP choose if client is inserted at head 
.br
\fIname\fP client name 
.br
\fIVAT\fP client VAT 
.br
\fIaddress\fP client address 
.br
\fIphone_number\fP client phone number 
.br
\fIbirth_day\fP client birth day 
.br
\fIbirth_month\fP client birth month 
.br
\fIbirth_year\fP client birth year 
.RE
.PP

.PP
Definition at line 54 of file client_linked_list\&.c\&.
.SS "void insert_client_sorted (\fBCLIENT_LL\fP * list, char * name, uint32_t VAT, char * address, uint32_t phone_number, int birth_day, int birth_month, int birth_year)"
insert a client into linked list sorted 
.PP
\fBParameters:\fP
.RS 4
\fIlist\fP linked list 
.br
\fIname\fP client name 
.br
\fIVAT\fP client VAT 
.br
\fIaddress\fP client address 
.br
\fIphone_number\fP client phone number 
.br
\fIbirth_day\fP client birth day 
.br
\fIbirth_month\fP client birth month 
.br
\fIbirth_year\fP client birth year 
.RE
.PP

.PP
Definition at line 79 of file client_linked_list\&.c\&.
.SS "void print_clients (\fBCLIENT_LL\fP * list)"
print all clients from linked list 
.PP
\fBParameters:\fP
.RS 4
\fIlist\fP linked list 
.RE
.PP

.PP
Definition at line 130 of file client_linked_list\&.c\&.
.SS "void read_list_bin (\fBCLIENT_LL\fP * list, char * filename)"
reads clients and their info ino linked list from \&.bin file 
.PP
\fBParameters:\fP
.RS 4
\fIlist\fP 
.br
\fIfilename\fP 
.RE
.PP

.PP
Definition at line 258 of file client_linked_list\&.c\&.
.SS "void read_list_txt (\fBCLIENT_LL\fP * list, char * filename)"
read clients into linked list from \&.txt file 
.PP
\fBParameters:\fP
.RS 4
\fIlist\fP linked list 
.br
\fIfilename\fP filename 
.RE
.PP

.PP
Definition at line 198 of file client_linked_list\&.c\&.
.SS "void remove_client (\fBCLIENT_LL\fP * list, char * client_name)"
removes a client from the linked list 
.PP
\fBParameters:\fP
.RS 4
\fIlist\fP linked list 
.br
\fIclient\fP client wanted 
.RE
.PP

.PP
Definition at line 98 of file client_linked_list\&.c\&.
.SS "void save_list_bin (\fBCLIENT_LL\fP * list, char * filename)"
save clients info into to -bin file 
.PP
\fBParameters:\fP
.RS 4
\fIlist\fP linked list 
.br
\fIfilename\fP filename 
.RE
.PP

.PP
Definition at line 267 of file client_linked_list\&.c\&.
.SS "void save_list_txt (\fBCLIENT_LL\fP * list, char * filename)"
save linked list info to \&.txt file 
.PP
\fBParameters:\fP
.RS 4
\fIlist\fP linked list 
.br
\fIfilename\fP filename 
.RE
.PP

.PP
Definition at line 229 of file client_linked_list\&.c\&.
.SS "\fBCLIENT\fP* search_client (\fBCLIENT_LL\fP * list, const char * client_name)"
searches for a client from the linked list 
.PP
\fBParameters:\fP
.RS 4
\fIlist\fP linked list 
.br
\fIclient_name\fP clients name 
.RE
.PP
\fBReturns:\fP
.RS 4
return client wanted 
.RE
.PP

.PP
Definition at line 86 of file client_linked_list\&.c\&.
.SS "void sort_clients (\fBCLIENT_LL\fP * list)"
sorts clients from linked list 
.PP
\fBParameters:\fP
.RS 4
\fIlist\fP linked list 
.RE
.PP

.PP
Definition at line 123 of file client_linked_list\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
