.TH "Porto_Pontos/Client_Node/client_node.c" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Porto_Pontos/Client_Node/client_node.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'client_node\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBset_client_name\fP (\fBCLIENT\fP *\fBclient\fP, char *name)"
.br
.ti -1c
.RI "void \fBset_client_address\fP (\fBCLIENT\fP *\fBclient\fP, char *address)"
.br
.ti -1c
.RI "\fBCLIENT_NODE\fP * \fBallocate_memory_node_client\fP ()"
.br
.ti -1c
.RI "void \fBdeallocate_memory_node_client\fP (\fBCLIENT_NODE\fP *node)"
.br
.ti -1c
.RI "\fBCLIENT\fP \fBcreate_client\fP (char *name, uint32_t VAT, char *address, uint32_t phone_number, int birth_day, int birth_month, int birth_year)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBCLIENT_NODE\fP* allocate_memory_node_client ()"
allocates memory for a client node 
.PP
\fBReturns:\fP
.RS 4
\fBclient_node\fP address 
.RE
.PP

.PP
Definition at line 12 of file client_node\&.c\&.
.SS "\fBCLIENT\fP create_client (char * name, uint32_t VAT, char * address, uint32_t phone_number, int birth_day, int birth_month, int birth_year)"
creates a client 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP name 
.br
\fIVAT\fP VAT 
.br
\fIaddress\fP address 
.br
\fIphone_number\fP phone number 
.br
\fIbirth_day\fP birth day 
.br
\fIbirth_month\fP birth month 
.br
\fIbirth_year\fP birth year 
.RE
.PP
\fBReturns:\fP
.RS 4
copy of client 
.RE
.PP

.PP
Definition at line 21 of file client_node\&.c\&.
.SS "void deallocate_memory_node_client (\fBCLIENT_NODE\fP * node)"
frees client node 
.PP
\fBParameters:\fP
.RS 4
\fInode\fP client node 
.RE
.PP

.PP
Definition at line 17 of file client_node\&.c\&.
.SS "void set_client_address (\fBCLIENT\fP * client, char * address)"

.PP
Definition at line 39 of file client_node\&.c\&.
.SS "void set_client_name (\fBCLIENT\fP * client, char * name)"

.PP
Definition at line 35 of file client_node\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
