.TH "Porto_Pontos/Date/date.c" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Porto_Pontos/Date/date.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'date\&.h'\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDATE\fP \fBinsert_registration_day\fP ()"
.br
.ti -1c
.RI "\fBDATE\fP \fBcreate_date\fP (int day, int month, int year)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBDATE\fP create_date (int day, int month, int year)"
creates a date (day/month/year) 
.PP
\fBParameters:\fP
.RS 4
\fIday\fP day 
.br
\fImonth\fP month 
.br
\fIyear\fP year 
.RE
.PP
\fBReturns:\fP
.RS 4
date 
.RE
.PP

.PP
Definition at line 22 of file date\&.c\&.
.SS "\fBDATE\fP insert_registration_day ()"
inserts the day/month/year of a client is inserted 
.PP
\fBReturns:\fP
.RS 4
date of registration 
.RE
.PP

.PP
Definition at line 9 of file date\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
