.TH "date" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
date \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <date\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBday\fP"
.br
.ti -1c
.RI "int \fBmonth\fP"
.br
.ti -1c
.RI "int \fByear\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file date\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int day"

.PP
Definition at line 9 of file date\&.h\&.
.SS "int month"

.PP
Definition at line 10 of file date\&.h\&.
.SS "int year"

.PP
Definition at line 11 of file date\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
