.TH "generation" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
generation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ag\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBid\fP"
.br
.ti -1c
.RI "\fBPOPULATION\fP * \fBparent\fP"
.br
.ti -1c
.RI "\fBPOPULATION\fP * \fBchild\fP"
.br
.ti -1c
.RI "\fBCHROMOSOME\fP * \fBfittest_chromosomes\fP"
.br
.ti -1c
.RI "struct \fBgeneration\fP * \fBnext_generation\fP"
.br
.ti -1c
.RI "\fBPOPULATION\fP \fBparent_population\fP"
.br
.ti -1c
.RI "\fBPOPULATION\fP \fBchild_population\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file ag\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBPOPULATION\fP* child"

.PP
Definition at line 30 of file ag\&.h\&.
.SS "\fBPOPULATION\fP child_population"

.PP
Definition at line 14 of file generation\&.h\&.
.SS "\fBCHROMOSOME\fP* fittest_chromosomes"

.PP
Definition at line 31 of file ag\&.h\&.
.SS "uint32_t id"

.PP
Definition at line 28 of file ag\&.h\&.
.SS "struct \fBgeneration\fP* next_generation"

.PP
Definition at line 32 of file ag\&.h\&.
.SS "\fBPOPULATION\fP* parent"

.PP
Definition at line 29 of file ag\&.h\&.
.SS "\fBPOPULATION\fP parent_population"

.PP
Definition at line 13 of file generation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
