.TH "gene" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gene \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ag\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file ag\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int id"

.PP
Definition at line 11 of file ag\&.h\&.
.SS "float x"

.PP
Definition at line 12 of file ag\&.h\&.
.SS "float y"

.PP
Definition at line 13 of file ag\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
