.TH "Genetic_Algorithm/Gene/gene.h" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Genetic_Algorithm/Gene/gene.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgene\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBgene\fP \fBGENE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGENE\fP * \fBallocate_memory_gene\fP (int size)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBgene\fP  \fBGENE\fP"

.SH "Function Documentation"
.PP 
.SS "\fBGENE\fP* allocate_memory_gene (int size)"
allocates memory for a gene array 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP array size 
.RE
.PP
\fBReturns:\fP
.RS 4
address of gene array 
.RE
.PP

.PP
Definition at line 8 of file gene\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
