.TH "Genetic_Algorithm/Generation/generation.c" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Genetic_Algorithm/Generation/generation.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'generation\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBparent_selection\fP (\fBPOPULATION\fP *\fBpopulation\fP, int num_elitism)"
.br
.ti -1c
.RI "void \fBcalculate_cumulative_probability\fP (\fBPOPULATION\fP *\fBpopulation\fP, float *cumulative_prob_arr)"
.br
.ti -1c
.RI "float \fBsum_population_fitness\fP (\fBPOPULATION\fP *\fBpopulation\fP)"
.br
.ti -1c
.RI "\fBCHROMOSOME\fP \fBfitness_selection\fP (\fBPOPULATION\fP \fBpopulation\fP, const float *cumulative_prob)"
.br
.ti -1c
.RI "float \fBfloat_in_range\fP (float min, float max)"
.br
.ti -1c
.RI "void \fBbreed\fP (\fBPOPULATION\fP *\fBpopulation\fP, int num_elitism)"
.br
.ti -1c
.RI "\fBCHROMOSOME\fP \fBcopy_chromosome\fP (\fBCHROMOSOME\fP \fBchromosome\fP)"
.br
.ti -1c
.RI "\fBCHROMOSOME\fP \fBcross_over\fP (\fBCHROMOSOME\fP *parent_one, \fBCHROMOSOME\fP *parent_two)"
.br
.ti -1c
.RI "\fBPOPULATION\fP \fBmutation\fP (\fBPOPULATION\fP \fBpopulation\fP, float mutation_prob)"
.br
.ti -1c
.RI "int \fBint_in_range\fP (int min, int max)"
.br
.ti -1c
.RI "void \fBswap_gene\fP (\fBGENE\fP *a, \fBGENE\fP *b)"
.br
.ti -1c
.RI "\fBPOPULATION\fP \fBinsert_first_population\fP (const \fBCOUNTRY\fP *booked_trip, int size_population)"
.br
.ti -1c
.RI "\fBPOPULATION\fP \fBinsert_child_population\fP (\fBGENERATION\fP *\fBgeneration\fP, int num_elitism, float mutation_prob)"
.br
.ti -1c
.RI "\fBPOPULATION\fP \fBdeep_copy_population\fP (\fBPOPULATION\fP *\fBpopulation\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void breed (\fBPOPULATION\fP * population, int num_elitism)"

.PP
Definition at line 204 of file generation\&.c\&.
.SS "void calculate_cumulative_probability (\fBPOPULATION\fP * population, float * cumulative_prob_arr)"

.PP
Definition at line 143 of file generation\&.c\&.
.SS "\fBCHROMOSOME\fP copy_chromosome (\fBCHROMOSOME\fP chromosome)"

.PP
Definition at line 237 of file generation\&.c\&.
.SS "\fBCHROMOSOME\fP cross_over (\fBCHROMOSOME\fP * parent_one, \fBCHROMOSOME\fP * parent_two)"

.PP
Definition at line 261 of file generation\&.c\&.
.SS "\fBPOPULATION\fP deep_copy_population (\fBPOPULATION\fP * population)"
copies every value of a population 
.PP
\fBParameters:\fP
.RS 4
\fIpopulation\fP population to copy 
.RE
.PP
\fBReturns:\fP
.RS 4
copied population 
.RE
.PP

.PP
Definition at line 71 of file generation\&.c\&.
.SS "\fBCHROMOSOME\fP fitness_selection (\fBPOPULATION\fP population, const float * cumulative_prob)"

.PP
Definition at line 184 of file generation\&.c\&.
.SS "float float_in_range (float min, float max)"

.PP
Definition at line 199 of file generation\&.c\&.
.SS "\fBPOPULATION\fP insert_child_population (\fBGENERATION\fP * generation, int num_elitism, float mutation_prob)"
inserts child population into generation 
.PP
\fBParameters:\fP
.RS 4
\fIgeneration\fP address of generation 
.br
\fInum_elitism\fP number of elitism 
.br
\fImutation_prob\fP mutation probability 
.RE
.PP
\fBReturns:\fP
.RS 4
child population 
.RE
.PP

.PP
Definition at line 52 of file generation\&.c\&.
.SS "\fBPOPULATION\fP insert_first_population (const \fBCOUNTRY\fP * booked_trip, int size_population)"
inserts first population into first generation 
.PP
\fBParameters:\fP
.RS 4
\fIbooked_trip\fP client booked trip 
.br
\fIsize_population\fP size of population 
.RE
.PP
\fBReturns:\fP
.RS 4
first population 
.RE
.PP

.PP
Definition at line 36 of file generation\&.c\&.
.SS "int int_in_range (int min, int max)"

.PP
Definition at line 332 of file generation\&.c\&.
.SS "\fBPOPULATION\fP mutation (\fBPOPULATION\fP population, float mutation_prob)"

.PP
Definition at line 302 of file generation\&.c\&.
.SS "void parent_selection (\fBPOPULATION\fP * population, int num_elitism)"

.PP
Definition at line 114 of file generation\&.c\&.
.SS "float sum_population_fitness (\fBPOPULATION\fP * population)"

.PP
Definition at line 175 of file generation\&.c\&.
.SS "void swap_gene (\fBGENE\fP * a, \fBGENE\fP * b)"

.PP
Definition at line 337 of file generation\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
