.TH "Genetic_Algorithm/Generation_Node/generation_node.h" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Genetic_Algorithm/Generation_Node/generation_node.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Generation/generation\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgeneration_node\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBgeneration_node\fP \fBGENERATION_NODE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGENERATION_NODE\fP * \fBallocate_memory_generation_node\fP (\fBGENERATION\fP \fBgeneration\fP)"
.br
.ti -1c
.RI "void \fBdeallocate_memory_generation_node\fP (\fBGENERATION_NODE\fP *node)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBgeneration_node\fP  \fBGENERATION_NODE\fP"

.SH "Function Documentation"
.PP 
.SS "\fBGENERATION_NODE\fP* allocate_memory_generation_node (\fBGENERATION\fP generation)"
allocates memory for a generation node 
.PP
\fBParameters:\fP
.RS 4
\fIgeneration\fP generation to insert 
.RE
.PP
\fBReturns:\fP
.RS 4
address of generation node 
.RE
.PP

.PP
Definition at line 19 of file generation_node\&.c\&.
.SS "void deallocate_memory_generation_node (\fBGENERATION_NODE\fP * node)"
frees generation node 
.PP
\fBParameters:\fP
.RS 4
\fInode\fP address of generation node 
.RE
.PP

.PP
Definition at line 26 of file generation_node\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
