.TH "Genetic_Algorithm/main_algorithm.c" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Genetic_Algorithm/main_algorithm.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'main_algorithm\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_last_generation_route\fP (\fBGENERATION_LL\fP *list)"
.br
.ti -1c
.RI "void \fBinitialize_algorithm\fP (const \fBCOUNTRY\fP *booked_trip, int num_iterations, int size_population, int num_elitism, float prob_mutation)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void initialize_algorithm (const \fBCOUNTRY\fP * booked_trip, int num_iterations, int size_population, int num_elitism, float prob_mutation)"
finds best route possible for client 
.PP
\fBParameters:\fP
.RS 4
\fIbooked_trip\fP booked trip 
.br
\fInum_iterations\fP number of algo iterations 
.br
\fIsize_population\fP population size 
.br
\fInum_elitism\fP elitism number 
.br
\fIprob_mutation\fP mutation probability 
.RE
.PP

.PP
Definition at line 15 of file main_algorithm\&.c\&.
.SS "void print_last_generation_route (\fBGENERATION_LL\fP * list)"

.PP
Definition at line 61 of file main_algorithm\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
