.TH "md_delivery" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_delivery \- Projeto LP1/AED1: 

.SS "Gestão de Viagens e Melhores Trajetos"
.PP
.SS "Aluno: Vitor Santos 38132"
.PP
.SS "Funcionalidades Implementados:"
.PP
.SS "R1:"
.PP
\&.a, \&.b, \&.c, \&.d, \&.f, \&.g 
.SS "R2:"
.PP
\&.a, \&.b
.PP
.SS "Funcionalidades parcialmente Implementados:"
.PP
.SS "R1:"
.PP
\&.e
.PP
.SS "Funcionalidades não implementadas:"
.PP
.SS "R2:"
.PP
\&.c 
