.TH "Porto_Pontos/Poi/poi.h" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Porto_Pontos/Poi/poi.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpoi\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBpoi\fP \fBPOI\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBpoi\fP \fBPOI\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
