.TH "points" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
points \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <points\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file points\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float x"

.PP
Definition at line 9 of file points\&.h\&.
.SS "float y"

.PP
Definition at line 10 of file points\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
