.TH "Porto_Pontos/Points/points.h" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Porto_Pontos/Points/points.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpoints\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBpoints\fP \fBPOINTS\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBpoints\fP \fBPOINTS\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
