.TH "population" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
population \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ag\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCHROMOSOME\fP * \fBchromosomes\fP"
.br
.ti -1c
.RI "int \fBnum_of_chromosomes\fP"
.br
.ti -1c
.RI "int \fBnum_chromosomes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file ag\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBCHROMOSOME\fP * \fBchromosomes\fP"

.PP
Definition at line 23 of file ag\&.h\&.
.SS "int num_chromosomes"

.PP
Definition at line 11 of file population\&.h\&.
.SS "int num_of_chromosomes"

.PP
Definition at line 24 of file ag\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
