.TH "Genetic_Algorithm/Population/population.c" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Genetic_Algorithm/Population/population.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'population\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBswap_cromo\fP (\fBCHROMOSOME\fP *a, \fBCHROMOSOME\fP *b)"
.br
.ti -1c
.RI "void \fBinsert_chromosomes\fP (\fBPOPULATION\fP *\fBpopulation\fP, const \fBCOUNTRY\fP *booked_trip)"
.br
.ti -1c
.RI "void \fBsort_chromosomes_by_fitness\fP (\fBPOPULATION\fP *\fBpopulation\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void insert_chromosomes (\fBPOPULATION\fP * population, const \fBCOUNTRY\fP * booked_trip)"
inserts chromosomes into population 
.PP
\fBParameters:\fP
.RS 4
\fIpopulation\fP address of population 
.br
\fIbooked_trip\fP client booked trip 
.RE
.PP

.PP
Definition at line 15 of file population\&.c\&.
.SS "void sort_chromosomes_by_fitness (\fBPOPULATION\fP * population)"
sort chromosomes by their fitness value 
.PP
\fBParameters:\fP
.RS 4
\fIpopulation\fP 
.RE
.PP

.PP
Definition at line 39 of file population\&.c\&.
.SS "void swap_cromo (\fBCHROMOSOME\fP * a, \fBCHROMOSOME\fP * b)"

.PP
Definition at line 59 of file population\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
