.TH "Tests/test_Description/test_description.c" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/test_Description/test_description.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'test_description\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain_test_description\fP (\fBCITY\fP *\fBcity\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main_test_description (\fBCITY\fP * city)"

.PP
Definition at line 8 of file test_description\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
