.TH "Tests/test_Files/test_Report/test_report.c" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/test_Files/test_Report/test_report.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'test_report\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain_test_report\fP (\fBCLIENT_LL\fP *list)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main_test_report (\fBCLIENT_LL\fP * list)"

.PP
Definition at line 7 of file test_report\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
