.TH "Tests/test_Cities/test_cities.h" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/test_Cities/test_cities.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Trips/trips\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain_test_cities\fP (\fBCOUNTRY\fP *\fBcountry\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main_test_cities (\fBCOUNTRY\fP * country)"

.PP
Definition at line 8 of file test_cities\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
