.TH "Tests/test_Files/test_BIN/test_bin.h" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/test_Files/test_BIN/test_bin.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Client_Linked_List/client_linked_list\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain_bin_test\fP (\fBCLIENT_LL\fP *list)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main_bin_test (\fBCLIENT_LL\fP * list)"

.PP
Definition at line 6 of file test_bin\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
