.TH "Tests/test_Trips/test_Booked_Trips/test_booked_trips.h" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/test_Trips/test_Booked_Trips/test_booked_trips.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Client/client\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain_test_booked_trips\fP (\fBCLIENT\fP *\fBclient\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main_test_booked_trips (\fBCLIENT\fP * client)"

.PP
Definition at line 7 of file test_booked_trips\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
