.TH "Tests/test_Files/test_TXT/test_txt.c" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/test_Files/test_TXT/test_txt.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'test_txt\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain_txt_test\fP (\fBCLIENT_LL\fP *list)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main_txt_test (\fBCLIENT_LL\fP * list)"

.PP
Definition at line 8 of file test_txt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
