.TH "Tests/test_POI/test_poi.h" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests/test_POI/test_poi.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Cities/cities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain_test_poi\fP (\fBCITY\fP *\fBcity\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main_test_poi (\fBCITY\fP * city)"

.PP
Definition at line 8 of file test_poi\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
