.TH "Porto_Pontos/Trips/trips.c" 3 "Mon Jan 10 2022" "TSP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Porto_Pontos/Trips/trips.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'trips\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCITY\fP * \fBallocate_memory_city\fP ()"
.br
.ti -1c
.RI "\fBCITY\fP * \fBreallocate_memory_city\fP (\fBCOUNTRY\fP *\fBcountry\fP)"
.br
.ti -1c
.RI "void \fBset_city_name\fP (\fBCITY\fP *\fBcity\fP, char *city_name, bool is_alloc)"
.br
.ti -1c
.RI "void \fBinsert_city\fP (\fBCOUNTRY\fP *\fBcountry\fP, char *city_name, float coordinate_x, float coordinate_y)"
.br
.ti -1c
.RI "void \fBremove_city\fP (\fBCOUNTRY\fP *\fBcountry\fP, char *city_name)"
.br
.ti -1c
.RI "void \fBedit_city\fP (\fBCOUNTRY\fP *\fBcountry\fP, char *current_city_name, char *new_city_name, float new_x, float new_y)"
.br
.ti -1c
.RI "\fBCITY\fP * \fBsearch_city\fP (\fBCOUNTRY\fP *\fBcountry\fP, char *city_name)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBCITY\fP * allocate_memory_city ()"

.PP
Definition at line 77 of file trips\&.c\&.
.SS "void edit_city (\fBCOUNTRY\fP * country, char * current_city_name, char * new_city_name, float new_x, float new_y)"
edits a city name and coordinates from country 
.PP
\fBParameters:\fP
.RS 4
\fIcountry\fP country 
.br
\fIcurrent_city_name\fP current city name 
.br
\fInew_city_name\fP new city name 
.br
\fInew_x\fP new coordinate x 
.br
\fInew_y\fP new coordinate y 
.RE
.PP

.PP
Definition at line 51 of file trips\&.c\&.
.SS "void insert_city (\fBCOUNTRY\fP * country, char * city_name, float coordinate_x, float coordinate_y)"
inserts a city into country 
.PP
\fBParameters:\fP
.RS 4
\fIcountry\fP country 
.br
\fIcity_name\fP city name to insert 
.br
\fIcoordinate_x\fP coordinate x 
.br
\fIcoordinate_y\fP coordinate y 
.RE
.PP

.PP
Definition at line 16 of file trips\&.c\&.
.SS "\fBCITY\fP * reallocate_memory_city (\fBCOUNTRY\fP * country)"

.PP
Definition at line 82 of file trips\&.c\&.
.SS "void remove_city (\fBCOUNTRY\fP * country, char * city_name)"
removes a city from country 
.PP
\fBParameters:\fP
.RS 4
\fIcountry\fP country 
.br
\fIcity_name\fP city name to remove 
.RE
.PP

.PP
Definition at line 36 of file trips\&.c\&.
.SS "\fBCITY\fP* search_city (\fBCOUNTRY\fP * country, char * city_name)"
searches for a city from country 
.PP
\fBParameters:\fP
.RS 4
\fIcountry\fP country 
.br
\fIcity_name\fP city name 
.RE
.PP
\fBReturns:\fP
.RS 4
address of city 
.RE
.PP

.PP
Definition at line 63 of file trips\&.c\&.
.SS "void set_city_name (\fBCITY\fP * city, char * city_name, bool is_alloc)"

.PP
Definition at line 90 of file trips\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TSP from the source code\&.
